version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/app.db
      - JWT_SECRET=your-super-secret-jwt-key-min-32-chars
      - ENVIRONMENT=development
      - ALLOWED_ORIGIN=http://localhost:3000
      - RATE_LIMIT=1000
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
